module.exports = {
  content: [
    "./src/**/*.{html,js,jsx,ts,tsx}",
    "./index.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#bec6e0",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "secondary": "#0058be",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d8e2ff",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#565e74",
        "on-background": "#191c1e",
        "tertiary-container": "#a4abc4",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-primary-fixed-variant": "#005321",
        "on-surface-variant": "#3d4a3d",
        "on-primary-container": "#004b1e",
        "primary-container": "#22c55e",
        "primary-fixed": "#6bff8f",
        "primary": "#006e2f",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#adc6ff",
        "inverse-primary": "#4ae176",
        "surface-container": "#eceef0",
        "outline": "#6d7b6c",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002109",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#383f54",
        "on-secondary-container": "#fefcff",
        "background": "#f7f9fb",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#4ae176",
        "secondary-container": "#2170e4",
        "surface-dim": "#d8dadc",
        "error": "#ba1a1a",
        "tertiary-fixed": "#dae2fd",
        "on-secondary-fixed": "#001a42",
        "outline-variant": "#bccbb9",
        "on-tertiary-fixed": "#131b2e",
        "on-error": "#ffffff",
        "surface-tint": "#006e2f"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "16px",
        "margin-mobile": "20px",
        "base": "4px",
        "sm": "8px",
        "gutter": "16px",
        "lg": "24px",
        "xl": "32px",
        "xs": "4px"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
